initial work
zlanguage/zcomp pull request #218
Opened 2020-10-15 03:06 UTC by RDIL

literally the bare bones of the refactor, obviously not done

2020-10-15 11:22 UTC, N8python commented
Looks pretty good - could you change the result of transpiling `loop` expressions back to `const`, rather than `var`? It is a scope thing.

2020-10-15 11:23 UTC, N8python reviewed
Looks pretty good as initial work.

2020-10-15 11:23 UTC, N8python requested changes
Looks pretty good as initial work.

2020-10-16 15:19 UTC, RDIL commented on packages/zcomp/src/compiler/gen.js
> +    r += `for (var ${iteree} of ${iterable}) {\n`;
```suggestion
    r += `for (const ${iteree} of ${iterable}) {\n`;
```

2020-10-19 17:50 UTC, merged